import{a as b,S,i as l}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",M="48844443-e0420521c284cbb6eb3a15b37";async function h(r,t){const a={q:r,key:M,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:40};try{return(await b.get(v,{params:a})).data}catch(s){throw console.error("API Fetching Error:",s),s}}const P=new S(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom",overlayOpacity:1,showCounter:!1});function p(r){const t=document.querySelector("#gallery"),a=r.map(({largeImageURL:s,webformatURL:e,tags:o,likes:c,views:y,comments:L,downloads:w})=>`
      <a href="${s}" class="gallery-item">
        <img src="${e}" alt="${o}" />
        <div class="image-info">
          <p><strong>Likes:</strong> ${c}</p>
          <p><strong>Views:</strong> ${y}</p>
          <p><strong>Comments:</strong> ${L}</p>
          <p><strong>Downloads:</strong> ${w}</p>
        </div>
      </a>`).join("");t.insertAdjacentHTML("beforeend",a),P.refresh()}function q(){var t;const r=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||100;window.scrollBy({top:r*2,behavior:"smooth"})}const n={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more-btn")};let u="",i=1;function g(){n.loader.classList.remove("hidden")}function d(){n.loader.classList.add("hidden")}function f(){n.loadMoreBtn.classList.remove("hidden")}function m(){n.loadMoreBtn.classList.add("hidden")}n.form.addEventListener("submit",async r=>{if(r.preventDefault(),u=n.input.value.trim(),i=1,n.gallery.innerHTML="",!u){l.error({message:"Please enter a search term!",position:"topRight",timeout:2e3}),m();return}g(),m();try{const t=await h(u,i);if(g(),t.hits.length===0){l.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3}),d(),r.target.reset();return}p(t.hits),d(),t.totalHits>i*40&&f()}catch(t){d(),n.gallery.innerHTML="",l.error({message:"Something went wrong! Please try again later.",position:"topRight",timeout:2e3}),console.error("Error fetching images:",t)}r.target.reset()});n.loadMoreBtn.addEventListener("click",async()=>{i+=1,g(),m();try{const r=await h(u,i);g(),p(r.hits),d(),f(),r.totalHits<=i*40&&(m(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})),q()}catch(r){d(),n.gallery.innerHTML="",l.error({message:"Something went wrong! Please try again later.",position:"topRight",timeout:2e3}),console.error("Error fetching images:",r)}});
//# sourceMappingURL=index.js.map
